import type { DesktopConfig } from "./types";

export const defaultConfig: DesktopConfig = {
  engine: {
    project: { name: "voxmaps-pollution-simulator", scenario_id: "scenario", random_seed: 42 },
    input: { flight_csv: null, column_mapping: {}, invalid_row_policy: "drop_and_report" },
    coordinates: {
      reference_mode: "first_valid_flight_point",
      reference_latitude: null,
      reference_longitude: null,
      reference_altitude_m: 0,
      flat_ground: true,
    },
    wind: {
      mode: "synthetic",
      minimum_numeric_coverage: 0.8,
      maximum_interpolation_gap_s: 30,
      height_adjustment_enabled: false,
      reference_height_m: 10,
      power_law_exponent: 0.143,
      synthetic: {
        base_speed_mps: 3,
        base_direction_from_deg: 270,
        speed_variability_mps: 0.5,
        direction_variability_deg: 10,
        gust_period_s: 60,
      },
    },
    source: {
      name: "demo_stack",
      latitude: null,
      longitude: null,
      offset_east_from_flight_centre_m: -150,
      offset_north_from_flight_centre_m: 0,
      ground_elevation_m: 0,
      stack_height_m: 60,
      plume_rise_m: 10,
      stack_diameter_m: 2,
      exit_velocity_mps: 12,
      exhaust_temperature_k: 423.15,
      ambient_temperature_k: 298.15,
      pm25_emission_g_s: 0.2,
      pm10_total_emission_g_s: 0.5,
      emission_start_s: 0,
      emission_end_s: null,
      emission_schedule: [],
    },
    simulation: {
      timestep_s: 1,
      trajectory_sample_interval_s: 1,
      particles_per_timestep: 20,
      warmup_s: 0,
      preflight_wind_policy: "none",
      horizontal_padding_m: 500,
      vertical_min_m: 0,
      vertical_max_m: 180,
      maximum_particles: 250000,
    },
    dispersion: {
      horizontal_diffusivity_m2_s: 5,
      vertical_diffusivity_m2_s: 1,
      fine_settling_velocity_mps: 0.001,
      coarse_settling_velocity_mps: 0.02,
      fine_deposition_velocity_mps: 0.001,
      coarse_deposition_velocity_mps: 0.01,
      fine_decay_rate_s: 0,
      coarse_decay_rate_s: 0,
    },
    voxel: { size_x_m: 20, size_y_m: 20, size_z_m: 10, smoothing_enabled: false, smoothing_radius_voxels: 1 },
    background: { pm25_ug_m3: 20, coarse_pm_ug_m3: 15 },
    sensor: {
      sample_interval_s: 1,
      response_time_pm25_s: 5,
      response_time_pm10_s: 5,
      transport_delay_s: 1,
      additive_noise_std_ug_m3: 1,
      multiplicative_noise_std_fraction: 0.03,
      calibration_slope_pm25: 1,
      calibration_slope_pm10: 1,
      calibration_offset_pm25_ug_m3: 0,
      calibration_offset_pm10_ug_m3: 0,
      bias_pm25_ug_m3: 0,
      bias_pm10_ug_m3: 0,
      quantization_ug_m3: 0.1,
      lower_detection_limit_ug_m3: 0,
      upper_saturation_limit_ug_m3: 1000,
      dropout_probability: 0,
      missing_value: null,
      humidity_interference_enabled: false,
      humidity_coefficient_fraction_per_pct: 0,
      rotor_wash_dilution_factor: 1,
      allow_physically_inconsistent_raw_sensor_noise: false,
    },
    output: { write_particle_ground_truth: true, parquet_compression: "snappy" },
    batch: null,
  },
  emissions: { pm25_emission_g_s: 0.2, coarse_pm_emission_g_s: 0.3 },
  background: { pm25_ug_m3: 20, pm10_ug_m3: 35 },
  wind_policy: { mode: "synthetic_fallback", interpolation: "linear_vector" },
  sensor_region: { size_x_m: 20, size_y_m: 20, size_z_m: 10 },
  playback: { frame_interval_s: 2, visualization_parcel_limit: 5000 },
  sensor_model: {
    pm25_noise_std_ug_m3: 1,
    pm10_noise_std_ug_m3: 1,
    pm25_bias_ug_m3: 0,
    pm10_bias_ug_m3: 0,
  },
};

export function cloneDefaultConfig(): DesktopConfig {
  return structuredClone(defaultConfig);
}
